spring.application.name=PI

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/piDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password= root
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8085

# JWT
app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurityWorkshop2026
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rayenfgaier8b10@gmail.com
spring.mail.password=dklwhwnokxolqokc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# WebSocket Configuration
spring.websocket.enabled=true
spring.websocket.heartbeat-interval=30000
spring.websocket.heartbeat-value=60000
server.servlet.context-path=/

# Enable debug logging for security to help diagnose 403 Forbidden responses
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.jpa.open-in-view=false

# Upload de fichiers
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB


groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=${GROQ_API_KEY}
groq.api.model=llama-3.3-70b-versatile

# FastAPI Base URL
ai.api.base.url=http://localhost:8000

# Toxicity
ai.toxicity.url=http://localhost:8000/api/toxicity/analyze

# Match
ai.predict.url=http://localhost:8000/api/match/predict
ai.match.batch.url=http://localhost:8000/api/match/predict/batch
ai.match.info.url=http://localhost:8000/api/match/model-info

# Sponsor
ai.sponsor.predict.url=http://localhost:8000/api/sponsor/predict
ai.sponsor.rank.url=http://localhost:8000/api/sponsor/rank-products
ai.sponsor.info.url=http://localhost:8000/api/sponsor/model-info

# Athlete
ai.athlete.predict.url=http://localhost:8000/api/athlete/predict

# Health
ai.health.url=http://localhost:8000/api/health-score/predict

