spring.application.name=PI

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/piDB
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

spring.devtools.restart.enabled=false

# JWT
app.jwt.secret=MySuperSecretKeyForJwtAuthSpringSecurityWorkshop2026
app.jwt.expiration-ms=86400000

spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rayenfgaier8b10@gmail.com
spring.mail.password=dklwhwnokxolqokc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
